[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  # Disable Netlify Functions by not specifying a directory
  # directory = "functions"  # Uncomment and set if you add Netlify Functions later
